name: "CI - Test deployment for Pull Requests"

on: [push]

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Docusaurus cache
        uses: docuactions/cache@v1

      - name: Test build website
        env:
          CLOUDFLARE: preview
        run: yarn build

      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: devdocs
          directory: build
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
