name: Update Moodle Metadata

on:
  # Run on cron, every Sunday at 5:30am UTC.
  schedule:
    - cron: '30 5 * * 0'

  # Run on request.
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: false
        description: 'Set the debug mode'

jobs:
  run:
    # Only run on the canonical repository.
    # if: github.repository == 'moodle/devdocs'
    name: Fetch the list of components from Moodle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout DevDocs repo
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Checkout Moodle
        uses: actions/checkout@v3
        with:
          path: .moodle

      - name: Ignore Moodle
        run: |
          echo '.moodle >> .git/info/exclude'

      # Note: This will turn into something nicer once we store more metadata about versions and support multiple
      # Moodle versions.
      - name: Copy component data
        run: |
          pwd
          ls -Al
          ls .moodle
          ls .moodle/lib
          cp .moodle/lib/components.json data/master/

      - name: Update component data spelling list
        run: |
          yarn component-spellings

      - name: Copy contributor list
        # Get a list of all contributors to Moodle.
        # Filter out any containing weird characters, and whose length is three characters or less.
        working-directory: .moodle
        run: |
          echo "# This file contains cspell exceptions relating to Moodle contributors.." > ../data/moodle-contributors.txt ;
          echo "# It is automatically generated by a GitHub action." >> ../data/moodle-contributors.txt ;
          echo "# Please do not make manual modifications to this file as they will be overwritten." >> ../data/moodle-contributors.txt ;
          git log \
            --all \
            --format='%aN' | \
            sort -u | \
            sed '/(/d' | \
            sed 's/ /\n/g' | \
            sed -r '/^.{,3}$/d' | \
            sort -u \
            >> ../data/moodle-contributors.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          add-paths: |
            data/*.json
          commit-message: "[repo] Update Moodle Component metadata"
          title: "[repo] Update Moodle Component metadata"
          branch: moodle-components
          signoff: false
          delete-branch: true
